---
output: rmarkdown::github_document
---

`moviemeter` : Tools to work with the MovieMeter API

Get an API key: <https://www.moviemeter.nl/site/registerclient/>

Read about their API <http://wiki.moviemeter.nl/index.php/API>

The following functions are implemented:

- `mm_get_movie_info`:	Retrieve film information
- `mm_search`:	Search for films
- `moviemeter_api_key`:	Get or set MOVIEMETER_API_KEY value

### Installation

```{r eval=FALSE}
devtools::install_git("https://github.com/hrbrmstr/moviemeter.git")
```

```{r message=FALSE, warning=FALSE, error=FALSE}
options(width=120)
```

### Usage

```{r message=FALSE, warning=FALSE, error=FALSE}
library(moviemeter)

# current verison
packageVersion("moviemeter")

mm_search("brave little toaster")

mm_get_movie_info(5208)
```

Generate a data frame for 3 movies (w/o useless fields):

```{r message=FALSE, warning=FALSE, error=FALSE}
library(purrr)

imdb_ids <- c("tt1107846", "tt0282552", "tt0048199")

df <- map_df(imdb_ids, ~mm_get_movie_info(.)[1:11])

dplyr::glimpse(df)
```

### Test Results

```{r message=FALSE, warning=FALSE, error=FALSE}
library(moviemeter)
library(testthat)

date()

test_dir("tests/")
```

